### ISSUE TITLE
Cannot debug Hello_1_World because there are multiple main classes

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/examples#2]
For running one of the 2 hello world applications you get a choice in SBT:

> %% helloworld/run
> [warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
> 
> Multiple main classes detected, select one to run:
> 
>  [1] subscript.example.HelloWorld
>  [2] subscript.example.Hello_1_World
> 
> Enter number: 2
> 
> [info] Running subscript.example.Hello_1_World
> Hello,
> world!

However, that does not work with the `ssDebug` command instead of `run`:

> %% helloworld/ssDebug
> [warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
> [trace] Stack trace suppressed: run last helloworld/*:ssDebug for the full output.
> [error](helloworld/*:ssDebug) java.util.NoSuchElementException: None.get
> [error] Total time: 0 s, completed 30-jan-2016 2:10:20

**Comment by anatoliykmetyuk** [comment]
The following worked for me:

```
MacBook-Pro-Anatolii:standard anatolii$ sbt
[info] Loading global plugins from /Users/anatolii/.sbt/0.13/plugins
[info] Loading project definition from /Users/anatolii/Projects/SubScript/examples/standard/project
[info] Set current project to root (in build file:/Users/anatolii/Projects/SubScript/examples/standard/)
> project helloworld
[info] Set current project to helloworld (in build file:/Users/anatolii/Projects/SubScript/examples/standard/)
> set mainClass in Compile := Some("subscript.example.Hello_1_World")
[info] Defining helloworld/compile:mainClass
[info] The new value will be used by helloworld/*:ssDebug, helloworld/*:ssDebugPure and 1 others.
[info]  Run `last` for details.
[info] Reapplying settings...
[info] Set current project to helloworld (in build file:/Users/anatolii/Projects/SubScript/examples/standard/)
> ssDebug
[info] Running subscript.swing.SubScriptDebugger subscript.example.Hello_1_World
debugger: subscript.swing.SubScriptDebugger$ on: subscript.example.Hello_1_World
```

**Comment by AndreVanDelft** [comment]
Could you clarify this in the README.md?
And add there a nested list of the relevant commands so that everyone can easily copy&paste?
I mean that the list should contain:

> project helloworld
> set mainClass in Compile := Some("subscript.example.HelloWorld")
> set mainClass in Compile := Some("subscript.example.Hello_1_World")

**Comment by anatoliykmetyuk** [comment]
I have updated the readme file with the [debug section](https://github.com/scala-subscript/examples#debugging-the-projects) - is it fine?

**Comment by AndreVanDelft** [comment]
Much better, though I would prefer also a complete list at the end, ready for copy+paste. 
Note: 

> You can use graphical debugger to 

should be 

> You can use a graphical debugger to 

See [this article](http://englishpage.com/articles/index.htm)

**Comment by anatoliykmetyuk** [comment]
[Done](https://github.com/scala-subscript/examples#commands-for-setting-the-main-class)
